/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlynhanvien;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Admin
 */
public class QuanLyNhanVienFrame extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyNhanVienFrame
     */
    public DanhSachNhanVien ds = new DanhSachNhanVien();

    public DefaultTableModel tableModel;
    String dateFormat = "dd/MM/yyyy";
    public QuanLyNhanVienFrame() throws ParseException {
        
        initComponents();
      
   
       NVQuanLy nvqltest = new NVQuanLy("q1","NamNH",new SimpleDateFormat(dateFormat).parse("06/10/2009"),3.5,"CTO",50000);
       ds.themNhanVien(nvqltest);
       NVBanHang nvbhtest = new NVBanHang("b2","NamNH BH",new SimpleDateFormat(dateFormat).parse("06/10/2015"),1.5,60);
       ds.themNhanVien(nvbhtest);
        NVBanHang nvbhtest1 = new NVBanHang("b3","ANamNH BH2",new SimpleDateFormat(dateFormat).parse("06/10/2012"),2.5,90);
       ds.themNhanVien(nvbhtest1);
       NVBanHang nvbhtest2 = new NVBanHang("b4","ANamNH BH3",new SimpleDateFormat(dateFormat).parse("02/11/2012"),1.8,40);
       ds.themNhanVien(nvbhtest2);
       
//       loadData(ds);
//       loadTable(ds);
    }

    private void loadTable(DanhSachNhanVien ds) throws ParseException{
        this.tableModel = (DefaultTableModel) jTable1.getModel();
        Object rowData[] = new Object[9];
        if(tableModel.getRowCount() < ds.danhSach.size()){
            for (int i = 0; i < ds.danhSach.size(); i++) {
                NhanVien nv = ds.danhSach.get(i);
                int stt = i;
                String maNhanVien = null;
                String tenNhanVien = null;
                Date ngayVaoLam = null;
                double heSoLuong = 0;
                String chucVu = null;
                double phuCapChucVu = 0;
                int soSanPhamBan = 0;
                double luongThucNhan = 0;
                if(nv instanceof NVBanHang){
                    NVBanHang nvbh = (NVBanHang) nv;

                    maNhanVien = nvbh.getMaNhanVien();
                    tenNhanVien = nvbh.getTenNhanVien();
                    ngayVaoLam = nvbh.getNgayVaoLam();
                    heSoLuong = nvbh.getHeSoLuong();
    //                chucVu = null;
    //                phuCapChucVu = 0;
                    soSanPhamBan = nvbh.getSoSanPhamBan();
                    luongThucNhan = nvbh.tinhLuongThucNhan();
                }
                if(nv instanceof NVQuanLy){
                    NVQuanLy nvql = (NVQuanLy) nv;

                    maNhanVien = nvql.getMaNhanVien();
                    tenNhanVien = nvql.getTenNhanVien();
                    ngayVaoLam = nvql.getNgayVaoLam();
                    heSoLuong = nvql.getHeSoLuong();
                    chucVu = nvql.getChucVu();
                    phuCapChucVu = nvql.getPhuCapChucVu();
    //                soSanPhamBan = 0;
                    luongThucNhan = nvql.tinhLuongThucNhan();
                }
                rowData[0] = stt+1;
                rowData[1] = maNhanVien;
                rowData[2] = tenNhanVien;
                rowData[3] = ngayVaoLam;
                rowData[4] = heSoLuong;
                rowData[5] = chucVu;
                rowData[6] = phuCapChucVu;
                rowData[7] = soSanPhamBan;
                rowData[8] = luongThucNhan;
                tableModel.addRow(rowData);
            }
        }
    }
    
    private Object[] loadColumnName(){
        return new Object[]{"STT","Mã Nhân Viên","Tên Nhân Viên","Ngày Vào Làm","Hệ Số Lương","Chức Vụ","Phụ Cấp Chức Vụ","Số Sản Phẩm Bán","Lương Thực Nhận"};
    }

//    {1,"q1","NamNH",new SimpleDateFormat(dateFormat).parse("06/10/2009"),3.5,"CTO",50000},
//            {2,"b2","NamNH BH",new SimpleDateFormat(dateFormat).parse("06/10/2015"),1.5,null,null,60}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdd = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnGet = new javax.swing.JButton();
        btnFindBest = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tfRemove = new javax.swing.JTextField();
        tfFind = new javax.swing.JTextField();
        tfMaNV = new javax.swing.JTextField();
        tfTenNV = new javax.swing.JTextField();
        tfNgayVaoLam = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfHeSoLuong = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfChucVu = new javax.swing.JTextField();
        tfPhuCapChucVu = new javax.swing.JTextField();
        tfSoSanPhamBan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DUY TÂN QUẢN LÝ SINH VIÊN");

        btnAdd.setText("THÊM");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnFind.setText("TÌM NHÂN VIÊN THEO MÃ");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnRemove.setText("XÓA NHÂN VIÊN THEO MÃ");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnGet.setText("HIỂN THỊ DANH SÁCH TẤT CẢ NHÂN VIÊN");
        btnGet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetActionPerformed(evt);
            }
        });

        btnFindBest.setText("TÌM NHÂN VIÊN BÁN HÀNG ĐƯỢC NHIỀU NHẤT");
        btnFindBest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindBestActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã Nhân Viên", "Tên Nhân Viên", "Ngày Vào Làm", "Hệ Số Lương", "Chức Vụ", "Phụ Cấp Chức Vụ", "Số Sản Phẩm Bán", "Lương Thực Nhận"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("MÃ NHÂN VIÊN");

        jLabel2.setText("NGÀY VÀO LÀM");

        jLabel4.setText("TÊN NHÂN VIÊN");

        jLabel6.setText("HỆ SỐ LƯƠNG");

        jLabel3.setText("CHỨC VỤ");

        jLabel5.setText("PHỤ CẤP CHỨC VỤ");

        jLabel7.setText("SỐ SẢN PHẨM BÁN");

        jLabel8.setText("NHÂN VIÊN QUẢN LÝ");

        jLabel9.setText("NHÂN VIÊN BÁN HÀNG");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfHeSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfPhuCapChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3))
                        .addGap(204, 204, 204)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 330, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGet)
                            .addComponent(btnFindBest)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnFind)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfFind, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRemove)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(tfSoSanPhamBan, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel4, jLabel6});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnGet))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFindBest))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFind)
                    .addComponent(tfFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemove)
                    .addComponent(tfRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfHeSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(tfChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSoSanPhamBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfPhuCapChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel4, jLabel6});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfHeSoLuong, tfMaNV, tfNgayVaoLam, tfTenNV});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetActionPerformed
        try {
            loadTable(ds);
        } catch (ParseException ex) {
            Logger.getLogger(QuanLyNhanVienFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGetActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < ds.danhSach.size(); i++) {
            if(ds.danhSach.get(i).getMaNhanVien().equals(tfRemove.getText())){
                ds.danhSach.remove(i);
                tableModel.removeRow(i);
                JOptionPane.showMessageDialog(null, "Xóa Thành Công");
            }
        }
        try {
            loadTable(ds);
        } catch (ParseException ex) {
            Logger.getLogger(QuanLyNhanVienFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        try {
            // TODO add your handling code here:
            loadTable(ds);
        } catch (ParseException ex) {
            Logger.getLogger(QuanLyNhanVienFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (int i = 0; i < tableModel.getRowCount(); i++) {
            if(tableModel.getValueAt(i,1).equals(tfFind.getText())){
                JOptionPane.showMessageDialog(null, "Đã tìm thấy Nhân Viên : " + tableModel.getValueAt(i,2).toString());
            }
        }
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnFindBestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindBestActionPerformed
        try {
            // TODO add your handling code here:
            loadTable(ds);
        } catch (ParseException ex) {
            Logger.getLogger(QuanLyNhanVienFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        int max = 0;
        int ma = 0;
        System.out.println("Hey 260");
       for (int i = 0; i < tableModel.getRowCount(); i++) {
            int soSanPhamBan = Integer.parseInt(tableModel.getValueAt(i,7).toString());
            if(soSanPhamBan > max){
                ma = i;
                max = soSanPhamBan;
            }
        }
        JOptionPane.showMessageDialog(null, "Nhân Viên bán được nhiều sản phẩm nhất là : " + tableModel.getValueAt(ma, 2));
    }//GEN-LAST:event_btnFindBestActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if(tfSoSanPhamBan.getText() == null){
            NVQuanLy nv = new NVQuanLy();
            nv.setMaNhanVien(tfMaNV.getText());
            nv.setTenNhanVien(tfTenNV.getText());
            try {
                nv.setNgayVaoLam(new SimpleDateFormat(dateFormat).parse(tfNgayVaoLam.getText()));
            } catch (ParseException ex) {
                Logger.getLogger(QuanLyNhanVienFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            nv.setHeSoLuong(Double.parseDouble(tfHeSoLuong.getText()));
            nv.setChucVu(tfChucVu.getText());
            nv.setPhuCapChucVu(Double.parseDouble(tfPhuCapChucVu.getText()));
            ds.themNhanVien(nv);
         
        } else {
            NVBanHang nv = new NVBanHang();
            nv.setMaNhanVien(tfMaNV.getText());
            nv.setTenNhanVien(tfTenNV.getText());
            try {
                nv.setNgayVaoLam(new SimpleDateFormat(dateFormat).parse(tfNgayVaoLam.getText()));
            } catch (ParseException ex) {
                Logger.getLogger(QuanLyNhanVienFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            nv.setHeSoLuong(Double.parseDouble(tfHeSoLuong.getText()));
            nv.setSoSanPhamBan(Integer.parseInt(tfSoSanPhamBan.getText()));
            ds.themNhanVien(nv);
        }
        try {
            loadTable(ds);
        } catch (ParseException ex) {
            Logger.getLogger(QuanLyNhanVienFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new QuanLyNhanVienFrame().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(QuanLyNhanVienFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnFindBest;
    private javax.swing.JButton btnGet;
    private javax.swing.JButton btnRemove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tfChucVu;
    private javax.swing.JTextField tfFind;
    private javax.swing.JTextField tfHeSoLuong;
    private javax.swing.JTextField tfMaNV;
    private javax.swing.JTextField tfNgayVaoLam;
    private javax.swing.JTextField tfPhuCapChucVu;
    private javax.swing.JTextField tfRemove;
    private javax.swing.JTextField tfSoSanPhamBan;
    private javax.swing.JTextField tfTenNV;
    // End of variables declaration//GEN-END:variables
}
